# Generated by Django 2.2.11 on 2020-04-11 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('carne', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('anno_creacion', models.CharField(max_length=4)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.Ciudad')),
                ('patrocinador_equipo', models.OneToOneField(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='futbol.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('anno_construccion', models.PositiveSmallIntegerField()),
                ('capacidad', models.IntegerField()),
                ('id_ciudad', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='1', max_length=40)),
                ('edad', models.CharField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador_Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ingreso', models.CharField(max_length=10)),
                ('min_salida', models.CharField(max_length=10)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iso', models.CharField(max_length=2, null=True)),
                ('nombre', models.CharField(max_length=46, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='persona_natural',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RolArbitro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('marcador', models.CharField(max_length=10)),
                ('empate', models.CharField(default='1', max_length=2, null=True)),
                ('arbitro', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='futbol.Arbitro')),
                ('equipo_local', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local_partido', to='futbol.Equipo')),
                ('equipo_visitante', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visitante_partido', to='futbol.Equipo')),
                ('estadio', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='futbol.Estadio')),
                ('ganador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='futbol.Equipo')),
                ('nombre_torneo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Otro_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minu', models.PositiveSmallIntegerField()),
                ('seg', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('jugador_principal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Jugador_Partido')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.Partido')),
            ],
        ),
        migrations.AddField(
            model_name='jugador_partido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.Partido'),
        ),
        migrations.CreateModel(
            name='Jugador_Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('equipo_actual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_equipo_equipo', to='futbol.Equipo')),
                ('equipo_anterior', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Equipo')),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='futbol.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Gol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minu', models.PositiveSmallIntegerField()),
                ('seg', models.PositiveSmallIntegerField()),
                ('Jugador_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.Jugador_Partido')),
                ('partido', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='futbol.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minu', models.PositiveSmallIntegerField()),
                ('seg', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('jugador_produjo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_falta_golpe_jugador_produjo', to='futbol.Jugador_Partido')),
                ('jugador_recibio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_falta_golpe_jugador_recibido', to='futbol.Jugador_Partido')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.Partido')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='patrocinador_persona_natural',
            field=models.OneToOneField(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='futbol.persona_natural'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='nombre_empresa', max_length=40, unique=True)),
                ('representante_legal', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('ciudad_sede_principal', models.OneToOneField(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Ciudad')),
                ('equipo_patrocinado', models.OneToOneField(default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Equipo')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Pais'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='rol',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.RolArbitro'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='tutor_de_arbitro',
            field=models.OneToOneField(default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='futbol.Arbitro'),
        ),
    ]
