# Generated by Django 2.2.11 on 2020-04-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='empate',
            field=models.CharField(default='--', max_length=2, null=True),
        ),
    ]
