# Generated by Django 2.2.11 on 2020-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0003_auto_20200419_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolarbitro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
